[build]
rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-unknown-linux-gnu]
linker = "x86_64-linux-gnu-gcc"

[target.x86_64-apple-darwin]
linker = "x86_64-apple-darwin-clang"

[target.aarch64-apple-darwin]
linker = "aarch64-apple-darwin-clang"
